apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: my-channel
  namespace: knative-demo
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 1
      replicationFactor: 1
