apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: offline-service
  namespace: kn-demo
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: quay.io/imaymon/quarkus-rest
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/imaymon/quarkus-rest
        name: ""
        resources: {}
      imagePullSecrets:
      - name: imaymon-imaymon-pull-pull-secret
status: {}
