apiVersion: v1
kind: Secret
metadata:
  name: imaymon-imaymon-pull-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhVzFoZVcxdmJpdHBiV0Y1Ylc5dVgzQjFiR3c2T1RCV1RFUlZORXhEU0RKTVRVUlNXak5HUXpaTVZqWlJVakJWTVRCWlIxaE1OVXRTUjBRNVMwMVRPVmhDVjBwWE1VODFPVkZLVlRkVU1WRXdVVEpITXc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
