apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: event-consumer
  namespace: knative-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 10s
        client.knative.dev/user-image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
      creationTimestamp: null
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
        name: ""
